<?php $this->partial("topo"); ?>
    
    <div style="margin-top: 50px !important;">
        <form action="" method="POST">
            
            <div class="row">
                <div class="col-md-6">
                    <input type="text" class="form-control preenche" name="pesquisa" id="pesquisa" placeholder="Pesquisar" value="<?php echo $pesquisa; ?>"/>
                </div>
                <div class="offset-md-4 col-md-2">
                    <a href="http://localhost/Projeto_Phalcon/Produto/inserir" class = "btn btn-primary preeche">
                        <i class="fas fa-plus" style="    margin-right: 5px;"></i>
                        Produto
                    </a>
                </div>
            </div>

            <div class="row espaco">
                <div class="col-md-12" style="margin-top: 30px">
                    <div class="form-group">
                    <table class="table table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Descrição</th>
                                <th scope="col" width="150px">Valor Custo</th>
                                <th scope="col" width="150px">Valor Venda</th>
                                <th class="text-center" scope="col" width="160px">Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($resultado as $item){ ?>
                                <tr>
                                    <td><?php echo $item->descricao;?></td> 
                                    <td><?php echo number_format($item->valor_custo, 2);?></td>
                                    <td><?php echo number_format($item->valor_venda, 2);?></td>
                                    <td class="text-center">
                                        <a href="http://localhost/Projeto_Phalcon/Produto/editar/<?php echo $item->id_produto;?>">
                                            <i class="fas fa-edit icone" style="margin-right: 30px"></i>
                                        </a>
                                        <a href="http://localhost/Projeto_Phalcon/Produto/desativar/<?php echo $item->id_produto;?>">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php }?>
                        </tbody>
                    </table>
                </div>
            </div>

        </form>
    </div>

<?php $this->partial("rodape"); ?>