<?php $this->partial("topo"); ?>

<div class="offset-md-1 col-md-10" style="margin-top: 30px !important">
    <h3>Novo Produto</h3>
    <hr />
</div>

<form action="http://localhost/Projeto_Phalcon/Produto/inserirDados" method="POST">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="form-group">
                <div class="row">

                    <div class="col-md-12">
                        <label>Descrição:</label>
                        <input type="text" class="form-control" required name="descricao" id="descricao"/>
                    </div>
                
                    <div class="col-md-6">
                        <label>Valor Custo:</label>
                        <input type="text" class="form-control" required name="valor_custo" id="valor_custo"/>
                    </div>
                    <div class="col-md-6">
                        <label>Valor Venda:</label>
                        <input type="text" class="form-control" required name="valor_venda" id="valor_venda"/>
                    </div>

                    <div class="offset-sm-8 col-md-2 espaco">
                        <input type="submit" value="Gravar" class="btn btn-primary preeche" />
                    </div>
                    <div class="col-md-2 espaco">
                        <a href="http://localhost/Projeto_Phalcon/Produto/" class="btn btn-danger preeche">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<?php $this->partial("rodape"); ?>