<?php $this->partial("topo"); ?>


    <div class="container">
        <div class="offset-3 col-md-6">
            <div class="row">
                <div class="col-md-12" style="margin-top: 30px;">
                    <h3>Remover Produto</h3>
                    <h6>Tem certeza que deseja remover?</h6>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="margin-top: 30px;">
                    <table class="table  table-hover">
                        <tr>
                            <th scope="col">Descrição</th>
                            <th scope="col">Valor Venda</th>
                        </tr>
                        <tr>
                            <td><?php echo $dados->descricao;?></td>
                            <td><?php echo $dados->valor_venda;?></td>
                        </tr>
                    </table>
                </div>
            </div>

            <form action="<?php echo 'http://localhost/Projeto_Phalcon/Produto/desativarDados/', $dados->id_produto; ?>" method="POST">

                <div class="row">
                    <div class="offset-2 col-md-4 espaco">
                        <input type="submit" value="Confimar" class="btn btn-primary preeche" />
                    </div>
                    <div class="col-md-4 espaco">
                        <a href="http://localhost/Projeto_Phalcon/Produto/" class="btn btn-danger preeche">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>


<?php $this->partial("rodape"); ?>