<?php 
use Phalcon\Tag;
$this->tag->getDoctype();
?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>titulo</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <div class="navbar-header navbar-brand">SISTEMA DE VENDAS</div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">VENDAS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="telaProduto">PRODUTOS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">CLIENTES</a>
                    </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <div class="container body-content">
            <form class="form-horizontal" action='../produto/' method='post'>
                <fieldset>
                
                <!-- Form Name -->
                <legend>Cadastro de Produtos</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="txtproduto">Produto</label>  
                    <div class="col-md-6">
                        <input id="txtproduto" name="txtproduto" type="text" placeholder="Descrição do Produto" class="form-control input-md" required="">   
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                <label class="col-md-4 control-label" for="txtestoque_minimo">Valor de Custo</label>  
                <div class="input-group col-md-4">
                <div class="input-group-prepend">
                    <span class="input-group-text">R$</span>
                </div>
                <input id="txtvalorcusto" name="txtvalorcusto" type="numeric" placeholder="" class="form-control input-md" required="">
                    
                </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                <label class="col-md-4 control-label" for="txtestoque_atual">Valor de Venda</label>  

                <div class="input-group col-md-4">
                <div class="input-group-prepend">
                    <span class="input-group-text">R$</span>
                </div>
                <input id="txtvalorvenda" name="txtvalorvenda" type="numeric" placeholder="" class="form-control input-md">
                    
                </div>
                </div>

                <!-- Button (Double) -->
                <div class="form-group">
                <label class="col-md-4 control-label" for="btnsalvar"></label>
                <div class="col-md-8">
                    <input id="btnsalvar" name="btnsalvar" type='submit' value='Salvar' class="btn btn-primary"/>
                    <button id="btncancelar" name="btncancelar" type="submit" class="btn btn-danger">Cancelar</button>
                </div>
                </div>
                </fieldset>
            </form>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
    </html>
