<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>titulo</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="navbar-header navbar-brand">SISTEMA DE VENDAS</div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">VENDAS</li>
                    <li class="nav-item">PRODUTOS</li>
                    <li class="nav-item">CLIENTES</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">