<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Titulo</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="navbar-header navbar-brand">SISTEMA DE VENDAS</div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link active" href="#">VENDAS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="#">PRODUTOS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="#">CLIENTES</a>
                  </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">