<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="stylesheet" href="http://localhost/Projeto_Phalcon/public/css/style.css" type="text/css" />
    
    <title>Phalcon</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="navbar-header navbar-brand">PHALCON</div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link active" href="http://localhost/Projeto_Phalcon/Cliente/">CLIENTES</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="http://localhost/Projeto_Phalcon/Funcionario/">FUNCIONÁRIOS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="http://localhost/Projeto_Phalcon/Produto/">PRODUTOS</a>
                  </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">